### ISSUE TITLE
Change color back to white background

### ISSUE THREAD

**Issue by lazengann86** [SHUR1K-N/Project-Pwnag0dchi#10]
Where's the line to change the color back to white background and black letters?

**Comment by SHUR1K-N** [comment]
https://github.com/SHUR1K-N/Project-Pwnag0dchi#i-dont-like-the-dark-mode-ui-how-do-i-make-the-ui-white-like-default

**Comment by lazengann86** [comment]
For some reason I thought that would invert the direction of the screen not the colors. Thanks!
