### ISSUE TITLE
default path to handshakes in display-password.py has changed

### ISSUE THREAD

**Issue by Talismancer** [SHUR1K-N/Project-Pwnag0dchi#13]
The path to handshakes in display-password.py points to /home/pi/handshakes
Result: "No cracked passwords."
It appears that the current default location has changed to /root/handshakes
Changing this gets it working again.

**Comment by SHUR1K-N** [comment]
Are you using the config.toml from this project, or your own/default?

**Comment by SHUR1K-N** [comment]
Closing this for now. If you still have issues, you can re-open this Issue. :)
