### ISSUE TITLE
Help with Macchanger on Pwnagotchi

### ISSUE THREAD

**Issue by ghost** [SHUR1K-N/Project-Pwnag0dchi#14]
Hello everyone,

This is not an issue, but a question. How can I change the MAC address of the external USB Wi-Fi interface? Previously, I modified the file using sudo nano /etc/rc.local, adding the line:

/sbin/ifconfig wlan0mon down; /usr/bin/macchanger -r wlan0mon; /sbin/ifconfig wlan0mon up

However, this file no longer exists in the current Pwnagotchi image. If anyone can help me, I would appreciate it.

I'm using the latest version jayofelony

I've tried many scripts, plugin and modified those and no lucky. 

I know I can do it manually, but I want to do it automatically on every boot.
Thanks!

**Comment by SHUR1K-N** [comment]
Since your question is directly related to jayofelony's latest image, you'll receive the best support on jayofelony's GitHub. Please open an Issue there.
