### ISSUE TITLE
enable_deauth shows errors in log

### ISSUE THREAD

**Issue by Roalkege** [SHUR1K-N/Project-Pwnag0dchi#6]
Hey,
after enabling the deauth plugin my log get spammed with
`[Enable_Deauth] ready: enabled deauth`
`enable deauth ui error: TypeError("View.set() missing 1 required positional argument: 'value'")`
`enable deauth ui error: TypeError("View.set() missing 1 required positional argument: 'value'")`...

**Comment by SHUR1K-N** [comment]
You can ignore it, I had to remove that argument from the plugin to reduce on-screen clutter from additional count values next to the ″D″ at the bottom. Might clean it up later to not show that in the log.
