### ISSUE TITLE
display-password not showing up on my Waveshare V4

### ISSUE THREAD

**Issue by Themistoklis24** [SHUR1K-N/Project-Pwnag0dchi#7]
I suggest on display -password plugin to add : 

elif ui.is_waveshare_v4
   H_pos = (0, 95)
   V_pos = (180, 61)

I put mine after line 30

After testing it on my pwni, the plugin showed up. I had to replace the previous plugin on both "available-plugins" and "custom plugins" folders.

**Comment by SHUR1K-N** [comment]
Added, thanks!

[Changes made](https://github.com/SHUR1K-N/Project-Pwnag0dchi/commit/9af94f27acfe20c85609067cd5cb911d4dabc6d5)
