### ISSUE TITLE
Alfa AWUS036AXM adapter supported?

### ISSUE THREAD

**Issue by Ademolght** [SHUR1K-N/Project-Pwnag0dchi#8]
Hi shurikenhack i want know if i can use this usb antenna for my pwnagotchi
https://alfa-network.eu/alfa-usb-adapter-awus036axm
Can u tell me if it's pssible to use it on my pwnagotchi?

**Comment by SHUR1K-N** [comment]
MediaTek chipset, so should be readily supported. But if not, you can install the drivers manually via SSH and it'll work.

Instructions [here](https://github.com/SHUR1K-N/Project-Pwnag0dchi#using-external-wi-fi-adapters).

**Comment by Ademolght** [comment]
cool thx and i have other question my rpi0 don't turn on this light when insert the sd card and in device manager i don't the devices can u help pls?

**Comment by SHUR1K-N** [comment]
Please keep the updated title so others with a similar question could find help more easily.
