### ISSUE TITLE
better_quickdic setup question

### ISSUE THREAD

**Issue by NoahJ008** [SHUR1K-N/Project-Pwnag0dchi#9]
Hi ive been playing w your plugins for a while and how do i configure dictionary attacks, as after reading your documentation im not sure if its setup and i have a wordlist that id like to add too anyway

**Comment by SHUR1K-N** [comment]
1. Create a test AP with a password that exists in a small dictionary TXT file that you've placed in the `/home/pi/wordlists/` directory. You can use mobile hotspot for this, with no additional security options enabled

2. Connect 1 client to the test AP, and let your Pwny deauth it + capture the handshake

3. If the handshake is valid, and `better_quickdic` is enabled, and a wordlist exists ― the cracking will immediately initiate in the background

NOTE: If a handshake is cracked using this plugin, it will NOT show on the Pwnagotchi screen (even with display-password enabled). You'll have to manually check the `/home/pi/handshakes` directory for any files that end in `.pcap.cracked`. More information on this in the documentation.

NOTE: You may see a very brief alert on the Pwny screen if the password was found. You can also see these messages by filtering ″quickdic″ in the logtail plugin.

NOTE: Use tiny wordlists only, the Pi Zero is not well-equipped enough to be running full-blown cracking; plus, it's also busy running Pwnagotchi.
